# -*- coding: utf-8 -*-
"""TF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Drw6FuH0UkH0hENODwO4hx510Wpetz8L
"""

!pip install --upgrade "tensorflow==1.7.*"

!git clone https://github.com/googlecodelabs/tensorflow-for-poets-2

cd tensorflow-for-poets-2

!curl http://download.tensorflow.org/example_images/flower_photos.tgz \
    | tar xz -C tf_files

IMAGE_SIZE=224
ARCHITECTURE="mobilenet_1.0_${IMAGE_SIZE}"

!python -m scripts.retrain -h

!python -m scripts.retrain \
  --model_dir=tf_files/models/ \
  --summaries_dir=tf_files/training_summaries/"mobilenet_1.0_224" \
  --output_graph=tf_files/retrained_graph.pb \
  --output_labels=tf_files/retrained_labels.txt \
  --architecture="mobilenet_1.0_224" \
  --image_dir=tf_files/flower_photos

!python -m scripts.label_image -h

!python -m scripts.label_image \
    --graph=tf_files/retrained_graph.pb  \
    --image=tf_files/flower_photos/daisy/img7.jpg

pwd

cd /content/tensorflow-for-poets-2

cd tf_files/flower_photos/daisy

!curl https://banner2.kisspng.com/20180612/exy/kisspng-silhouette-tulip-clip-art-black-and-white-flower-5b208e562649c8.7042367415288602461568.jpg> img7.jpg